---
title: Blog's
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
owner: eggoez
email: eggoez@teknik.io
img: https://avatars2.githubusercontent.com/u/8485824?s=400&v=4
description: 'Everything will be changed!

'
baseurl: "/blog"
url: https://eggoez.github.io
permalink: "/:categories/:title.html"
twitter_username: eggoez
github_username: eggoez
markdown: kramdown
