---
layout: page
title: Baguz Ach
permalink: /eggoez/
---
<p><a href="https://eggoez.bitbucket.io/wp-content/uploads/2011/08/IMG_0975.jpg" class="fancybox image"><img class="size-medium wp-image-636 alignleft" alt="IMG_0975" src="https://eggoez.bitbucket.io/wp-content/uploads/2011/08/IMG_0975-300x168.jpg" width="300" height="168"></a>Hai, nama saya Baguz, biasa di panggil yang akrab ditelinga saya goez dan eggo, atau panggil saja baguz, saya tidak memiliki otak yang cerdas seperti manusia pada umumnya termasuk Anda,&nbsp; karena saya memerlukan waktu yang lebih lama untuk memahami sesuatu dibandingkan dengan otak manusia pada umumnya, tapi itu bukan halangan bagi saya, bahkan kekurangan saya tersebut menjadi pembangkit semangat saya untuk menjalani hari demi hari untuk belajar, belajar dan belajar dengan lebih giat di bandingkan manusia pada umumnya. Namun pada akhirnya saya tetap saja merasa seperti seorang idiot dan eggo. Saya dulu dilahirkan di Jember, Indonesia, saya dulu pernah menduduki bangku di MI Al Islah Jatiagung, SMP Negeri 3 Wonorejo, SMKT Balung, dan Jurusan Desain Grafis Komputer ( Wearnes Education Center ) Malang, angkatan 2009, mungkin ini suatu keputusan yang salah, karena pada akhirnya saya lebih tertarik pada dunia Teknologi Informatika daripada dunia otomotif dan desain, saya juga sedang mencoba sedikit belajar kode HTML, PHP dan CSS di bidang desain web secara otodidak, sedikit pula belajar menjadi manusia yang lebih baik. tapi jujur semua itu bukan merupakan bidang saya, tapi saya berhasil melakukannya. Hal apapun itu yang kita yakini <strong>bisa</strong> pasti <strong>bisa</strong> kita lakukan, asalkan terus belajar, berusaha dan berdoa tentunya. That’s the point. Life is NOT always about skills. Sometimes the person who wins is the person who believe he/she can win! Kebuntuan-kebuntuan ini membuat hari-hari saya sungguh bermakna. Karena pasti ada suatu penjelasan dari suatu masalah yang tidak dapat saya pecahkan. saya menulis di blog ini sekedar untuk mengisi waktu luang dan belajar serta mencatat sedikit tentang apa yang saya tahu dan bisa, berbagi itu lebih baik, walaupun sedikit yang kita tahu, daripada menyimpan sendiri. sharing is better, although slightly, than our own store :D</p>
<p>Hobby saya adalah tertawa, travelling, gowes, tidur, internet, writing, programing, web designer, blogging,&nbsp; basketball and sometimes want to be alone.</p>
<p>About me: Coffe drinker. Nerd. Skeptic. Information seeker. Computer addict. Smartest to become an idiot.</p>
<p>Only a dreamer and i’m not the only one.</p>
<p>Senang berkenalan dengan anda <img src="https://eggoez.bitbucket.io/wp-content/emojione/png/1f643.png" alt=":)" class="emojione" style="font-size:inherit;height:3ex;width:3.1ex;min-height:20px;min-width:20px;display:inline-block;margin:-.2ex .15em .2ex;line-height:normal;vertical-align:middle"></p>
<p><em> </em><br>
<a title="Cari informasi lebih banyak tentang eggoez" href="http://bgz.bl.ee/about" target="_blank">Who i’m?</a></p>